[build]
  [build]
  base = "frontend"
  command = "npm ci && npx vite build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://banking-back-pqlr.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
