[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm ci && npm run build"  # npm ci is cleaner than npm install

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE_URL = "https://banking-back-pqlr.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
