[build]
  base = "frontend"            # points to the Vite project folder
  publish = "dist"             # Vite outputs to dist inside the base folder
  command = "npm install && npx vite build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE_URL = "https://banking-back-pqlr.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
