[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm install -g vite && vite build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE_URL = "https://banking-back-pqlr.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
