services:
  - type: web
    name: banking-backend
    runtime: node
    plan: starter
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromService:
          type: mongodb
          name: banking-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://primewavebank.netlify.app
  - type: mongodb
    name: banking-db
    plan: free
